stages:
  - deploy

deploy_izr_website:
  stage: deploy
  variables:
    TARGET: website
  trigger:
    include: 
      - project: izr-production/izr-server
        file: .gitlab-ci.yml
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'