name: Build and Push Docker Image

on:
  push:
    branches:
      - main # trigger only on main branch merges

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Define version (using run number + short commit sha)
      - name: Set image version
        id: vars
        run: |
          VERSION="${GITHUB_RUN_NUMBER}-${GITHUB_SHA::7}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # Build Docker image
      - name: Build Docker image
        env:
          VITE_API_BASE_URL: ${{ vars.VITE_API_BASE_URL }}
          VITE_MOSQUE_NAME: ${{ vars.VITE_MOSQUE_NAME }}
        run: |
          docker build \
            --build-arg VITE_API_BASE_URL="${VITE_API_BASE_URL}" \
            --build-arg VITE_MOSQUE_NAME="${VITE_MOSQUE_NAME}" \
            -t ${{ secrets.DOCKER_USERNAME }}/izr-website:${{ steps.vars.outputs.version }} \
            .
          docker tag ${{ secrets.DOCKER_USERNAME }}/izr-website:${{ steps.vars.outputs.version }} ${{ secrets.DOCKER_USERNAME }}/izr-website:latest

      # Push Docker image
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/izr-website:${{ steps.vars.outputs.version }}
          docker push ${{ secrets.DOCKER_USERNAME }}/izr-website:latest
